Fully specify clone technical name and possibility to disable deregistration
xebialabs-community/xld-websphere-portal-plugin pull request #3
Opened 2017-10-16 13:28 UTC by maartenhurkens

Hi,

In working with the plugin we came to a conclusion we needed two more requirements:

1. Option to disable deregistration of portlets. This is needed in the usecase that you want to change the underlying application name of the registered portlets without unregistering the portlet, therefore removing the portlet from any personal page we let our users edit.
2. Some teams wanted to have more control of the clone name, which is a technical key within portal. So when adding "$cloned" somewhere in the clonename, now the full name is used instead of the generated <portlet>.$cloned.<clonename>.

Tested the updated plugin in old usescases and new, and didn't encounter any error.

Please review.

regards, Maarten

2017-10-16 14:00 UTC, ravan requested changes

2017-10-16 14:00 UTC, ravan commented on src/main/resources/synthetic.xml
> +        <property name="disableDeregisterOnUninstall" kind="boolean" required="true" label="Disable deregistration on uninstall"
When used in the deployable (wp.War), it is best to have this field as not required and of kind string.  Then you will also be able to use a placeholder and drive the functionality from dictionaries if required.

2017-10-17 14:58 UTC, maartenhurkens commented
Fixed according to review. (added an extra checkin because somehow GitHub didn't pickup the change in the pull request, so I thought I did something wrong...)

2017-10-17 15:03 UTC, merged

2017-10-17 15:04 UTC, ravan commented
Thank you so much Maarten for your contribution to this plugin.  It is really appreciated.